server:
  port: 8005
  ssl:
    enabled: true
    key-store: src/main/resources/ingestion-service-keystore.p12
    key-store-password: iampass
    key-store-type: PKCS12
    key-alias: ingestion-service

    # 🔑 Truststore (so user-service trusts Eureka's certificate)
    trust-store: src/main/resources/truststore.p12
    trust-store-password: iampass
    trust-store-type: PKCS12

spring:
  application:
    name: ingestion-service

  datasource:
    url: jdbc:mysql://localhost:3306/routely
    username: root
    password: Iamroot@123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update   # Optional: create, create-drop, validate, update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
eureka:
  instance:
    hostname: localhost
    secure-port-enabled: true
    secure-port: 8005
    non-secure-port-enabled: false
    prefer-ip-address: false
    instance-id: ${spring.application.name}:${server.port}
    metadata-map:
     secure: "true"  

  client:
    register-with-eureka: true   # server itself doesn’t register
    fetch-registry: true
    service-url:
      defaultZone: https://localhost:8761/eureka/
