const WebSocketAction = {
        // Driver WebSocket Actions
    DRIVER_WEBSOCKET_ACTIONS : {
        DRIVER_ACCEPT_A_RIDE : "DRIVER_ACCEPT_A_RIDE",
        DRIVER_ARRIVED : "DRIVER_ARRIVED",
        START_TRIP : "DRIVER_START_TRIP",
        COMPLETE_TRIP : "DRIVER_COMPLETE_TRIP",
        CANCEL_TRIP : "DRIVER_CANCEL_TRIP",
        DECLINE_TRIP : "DRIVER_DECLINE_TRIP",
        DRIVER_LOCATION_PUSH : "DRIVER_LOCATION_PUSH",
        RIDE_OFFERED : "RIDE_OFFERED",
        RIDE_REQUEST : "RIDE_REQUEST",
    },

    //User WebSocket Actions
    USER_WEBSOCKET_ACTIONS : {
        USER_REQUEST_RIDE : "USER_REQUEST_RIDE",
        USER_CANCEL_RIDE : "USER_CANCEL_RIDE",
        USER_RIDE_STATUS_UPDATE : "USER_RIDE_STATUS_UPDATE",
        USER_LOCATION_PUSH : "USER_LOCATION_PUSH",
        USER_RIDE_ACCEPTED_BY_DRIVER : "RIDE_ACCEPTED_BY_DRIVER",
        USER_LOCATION_SYNC : "USER_LOCATION_SYNC",
        AVAILABLE_DRIVER : "AVAILABLE_DRIVER"
    }
};

export default WebSocketAction;